"""add clientes perfiles matches

Revision ID: 576d8eb9b98b
Revises: 2c94678d6daf
Create Date: 2026-04-23 17:37:08.161563

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# Identificadores de esta migración. No los toques a mano.
revision: str = '576d8eb9b98b'
down_revision: Union[str, None] = '2c94678d6daf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Aplica esta migración."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clientes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('perfiles_interes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.Column('palabras_clave', sa.Text(), nullable=True),
    sa.Column('cpv_prefijos', sa.String(length=200), nullable=True),
    sa.Column('presupuesto_min', sa.Float(), nullable=True),
    sa.Column('presupuesto_max', sa.Float(), nullable=True),
    sa.Column('provincias', sa.Text(), nullable=True),
    sa.Column('descripcion_ia', sa.Text(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('matches',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('licitacion_id', sa.String(length=512), nullable=False),
    sa.Column('perfil_id', sa.Integer(), nullable=False),
    sa.Column('paso_filtro_a', sa.Boolean(), nullable=False),
    sa.Column('score_ia', sa.Integer(), nullable=True),
    sa.Column('razon_ia', sa.Text(), nullable=True),
    sa.Column('notificado', sa.Boolean(), nullable=False),
    sa.Column('notificado_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['licitacion_id'], ['licitaciones.id'], ),
    sa.ForeignKeyConstraint(['perfil_id'], ['perfiles_interes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('matches', schema=None) as batch_op:
        batch_op.create_index('ix_matches_licitacion_perfil', ['licitacion_id', 'perfil_id'], unique=True)
        batch_op.create_index('ix_matches_notificado', ['notificado'], unique=False)
        batch_op.create_index('ix_matches_perfil_id', ['perfil_id'], unique=False)

    with op.batch_alter_table('licitaciones', schema=None) as batch_op:
        batch_op.add_column(sa.Column('texto_extraido', sa.Text(), nullable=True))
        batch_op.alter_column('nif_organo',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=30),
               existing_nullable=True)
        batch_op.alter_column('estado_contrato',
               existing_type=sa.VARCHAR(length=80),
               type_=sa.String(length=20),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Revierte esta migración."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('licitaciones', schema=None) as batch_op:
        batch_op.alter_column('estado_contrato',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=80),
               existing_nullable=True)
        batch_op.alter_column('nif_organo',
               existing_type=sa.String(length=30),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)
        batch_op.drop_column('texto_extraido')

    with op.batch_alter_table('matches', schema=None) as batch_op:
        batch_op.drop_index('ix_matches_perfil_id')
        batch_op.drop_index('ix_matches_notificado')
        batch_op.drop_index('ix_matches_licitacion_perfil')

    op.drop_table('matches')
    op.drop_table('perfiles_interes')
    op.drop_table('clientes')
    # ### end Alembic commands ###