"""add clientes perfiles matches

Revision ID: 25fca80de537
Revises: 4ca0e8bf27aa
Create Date: 2026-04-23 18:56:26.742485

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# Identificadores de esta migración. No los toques a mano.
revision: str = '25fca80de537'
down_revision: Union[str, None] = '4ca0e8bf27aa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Aplica esta migración."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revierte esta migración."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###