"""add texto_extraido column

Revision ID: 4ca0e8bf27aa
Revises: b1e4e3f357d3
Create Date: 2026-04-23 18:24:35.932975

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# Identificadores de esta migración. No los toques a mano.
revision: str = '4ca0e8bf27aa'
down_revision: Union[str, None] = 'b1e4e3f357d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Aplica esta migración."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revierte esta migración."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###