"""baseline initial schema

Revision ID: 2c94678d6daf
Revises: 
Create Date: 2026-04-23 15:18:47.594662

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# Identificadores de esta migración. No los toques a mano.
revision: str = '2c94678d6daf'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Aplica esta migración."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('licitaciones',
    sa.Column('id', sa.String(length=512), nullable=False),
    sa.Column('titulo', sa.Text(), nullable=False),
    sa.Column('link_plataforma', sa.Text(), nullable=True),
    sa.Column('fecha_publicacion', sa.DateTime(), nullable=True),
    sa.Column('fecha_actualizacion', sa.DateTime(), nullable=True),
    sa.Column('organo_contratacion', sa.Text(), nullable=True),
    sa.Column('nif_organo', sa.String(length=30), nullable=True),
    sa.Column('tipo_contrato', sa.String(length=100), nullable=True),
    sa.Column('presupuesto_base', sa.Float(), nullable=True),
    sa.Column('valor_estimado', sa.Float(), nullable=True),
    sa.Column('cpv_codigo', sa.String(length=20), nullable=True),
    sa.Column('cpv_descripcion', sa.Text(), nullable=True),
    sa.Column('lugar_ejecucion', sa.Text(), nullable=True),
    sa.Column('estado_contrato', sa.String(length=20), nullable=True),
    sa.Column('expediente', sa.String(length=120), nullable=True),
    sa.Column('estado_proceso', sa.String(length=30), nullable=False),
    sa.Column('url_pdf_ppt', sa.Text(), nullable=True),
    sa.Column('url_pdf_pca', sa.Text(), nullable=True),
    sa.Column('nombre_pdf', sa.Text(), nullable=True),
    sa.Column('ruta_pdf_local', sa.Text(), nullable=True),
    sa.Column('resumen_ia', sa.Text(), nullable=True),
    sa.Column('es_relevante', sa.Boolean(), nullable=True),
    sa.Column('error_msg', sa.Text(), nullable=True),
    sa.Column('raw_summary_html', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('licitaciones', schema=None) as batch_op:
        batch_op.create_index('ix_licitaciones_cpv', ['cpv_codigo'], unique=False)
        batch_op.create_index('ix_licitaciones_estado_proceso', ['estado_proceso'], unique=False)
        batch_op.create_index('ix_licitaciones_fecha_pub', ['fecha_publicacion'], unique=False)
        batch_op.create_index('ix_licitaciones_organo', ['organo_contratacion'], unique=False)

    op.create_table('log_ejecuciones',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('feed_url', sa.Text(), nullable=False),
    sa.Column('timestamp_inicio', sa.DateTime(), nullable=False),
    sa.Column('timestamp_fin', sa.DateTime(), nullable=True),
    sa.Column('total_entradas_feed', sa.Integer(), nullable=True),
    sa.Column('nuevas_insertadas', sa.Integer(), nullable=True),
    sa.Column('ya_existian', sa.Integer(), nullable=True),
    sa.Column('errores', sa.Integer(), nullable=True),
    sa.Column('estado_run', sa.String(length=20), nullable=False),
    sa.Column('mensaje', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revierte esta migración."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('log_ejecuciones')
    with op.batch_alter_table('licitaciones', schema=None) as batch_op:
        batch_op.drop_index('ix_licitaciones_organo')
        batch_op.drop_index('ix_licitaciones_fecha_pub')
        batch_op.drop_index('ix_licitaciones_estado_proceso')
        batch_op.drop_index('ix_licitaciones_cpv')

    op.drop_table('licitaciones')
    # ### end Alembic commands ###