"""add texto_extraido column

Revision ID: b1e4e3f357d3
Revises: 576d8eb9b98b
Create Date: 2026-04-23 18:21:34.824888

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# Identificadores de esta migración. No los toques a mano.
revision: str = 'b1e4e3f357d3'
down_revision: Union[str, None] = '576d8eb9b98b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Aplica esta migración."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revierte esta migración."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###